import type { Metadata } from "next"
import "./globals.css"
import Header from "./components/Header"
import Footer from "./components/Footer"
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="uk">
      <body className={`${montserrat.variable}`}>
        <div className="flex flex-col min-h-[100%]">
          <Header/>
          <main className="flex-grow pt-44 custom-container">
            <div>
              <h3>First</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
            </div>
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
