import type { Metadata } from "next"
import "./globals.css"
import Header from "./components/Header"
import Footer from "./components/Footer"
import { Montserrat } from 'next/font/google'
import StoreProvider from "./StoreProvider"

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="uk">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="preload" href="/images/hero-background.jpg" as="image"></link>
      </head>
      <body className={`${montserrat.variable}`}>
        <StoreProvider>
          <div className="flex flex-col min-h-[100%] bg-project-white">
            <Header/>
            <main className="flex-grow">
              {/* <div>
              <h3>First</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              <h3>I</h3>
              </div> */}
              {children}
            </main>
            <Footer/>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
